name: Docker Build/Publish Image 
on:  
  push:    
    branches: [ master ]  

jobs:   
  build-docker-image:    
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout the code       
        uses: actions/checkout@v2
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Prepare image name
        run: |
          echo "DOCKER_IMAGE=$GITHUB_REPOSITORY:1.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}, ${{ env.GITHUB_REPOSITORY}}:latest
          platforms: linux/arm/v7
